### PR TITLE
Adding github pr-badges, PR template and validation template

### PR DESCRIPTION
**Pull request by juanangp**
Added PR badges, PR template and validation template.
- Implemented `github actions` and `status` check
- The [`validation.yml`](https://github.com/rest-for-physics/restDAQ/blob/328b70bb0d7d716835bb47e921230ac349fdefd4/.github/workflows/validation.yml) file can be used as template to migrate from `gitlab` pipeline to `github`. Currently it performs the following actions:
  - Checkout `framework` branch matching feature branch (otherwise master)
  - `pull-submodules` with feature branch
  - Build and install the code
  - Install artifacts

### CODE REVIEW

**Comment by jgalan** [comment]
Why not on GitLab?

**Comment by juanangp** [comment]
> Why not on GitLab?

Because github requires some actions checks enabled to force the merge with master in a PR.

Also, I think that is more consistent because our repository lies Github.

Sorry for the spam...

**Comment by jgalan** [comment]
Still, will you be able to block merging of this PR if validation at another repo fails?

**Comment by juanangp** [comment]
> Still, will you be able to block merging of this PR if validation at another repo fails?

Yes, we can actually define which status check needs to pass before merging.

image

**Review by jgalan — APPROVED** [review]

**Pull request merged**
